### ISSUE TITLE
Can we switch to this patched version?

### ISSUE THREAD

**Issue by natoe33** [ubports/ofono#15]
https://git.sr.ht/~anteater/ofono

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/packaging/ofono/-/issues/1

Sorry for your inconvenience.
