### ISSUE TITLE
Creating new APN wipes out settings first time, saves after re-editing

### ISSUE THREAD

**Issue by rik-shaw** [ubports/ofono#24]
Before today, on a Pixel 3a XL (Halium 9), I wasn't able to create a new APN setting with the GUI. Also other settings would get reverted sometimes. Anyway, thanks to changes today, the GUI settings are able to be changed much better.

One problem, however. When creating a new APN entry and filling out the details and saving and closing, it wipes out the details and changes the APN name to "MMS" or "Internet". Re-editing that new APN and changing the APN name and settings, and then saving, results in the changes correctly "sticking" this second time.

So, functionality is there, but only with persistence of re-editing after the first attempt was not saved correctly.

**Comment by rik-shaw** [comment]
This is still the case with the "usissue" ofono patch. A newly created APN entry will have its initially inserted data discarded the FIRST time (when creating it), leaving the name a generic "MMS" or "Internet". But the entry is at least created, and can then be re-entered and edited. This is an improvement as without this fix it is often (always?) not possible to create an APN at all.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/packaging/ofono-sailfish/-/issues/1

Sorry for your inconvenience.
