### ISSUE TITLE
Network provider signal not detected

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ofono#31]
On Redmi Note 8 Pro after input SIM code signal wont appear unless i go to settings and select manual the type of signal 2G/3G etc.
I does get signal i just restart ofono  service.
Using Halium 10

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/packaging/ofono-sailfish/-/issues/3

Sorry for your inconvenience.
