### ISSUE TITLE
Change Mobile Broadband Provider Info upstream to GNOME

### ISSUE THREAD

**Issue by rik-shaw** [ubports/ofono#33]
https://gitlab.gnome.org/GNOME/mobile-broadband-provider-info

@Flohack74 suggested it is better to use upstream GNOME for this db rather than Sailfish. Here is his comment:

> "I think we should pull this db from GNOME rather than any of the downstreams in between as we will otherwise always have heavily outdated data. The disadvantage if you repackage already repackaged things ;)"

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/focal-projectmanagement-missing-packages/-/issues/77

Sorry for your inconvenience.
