### ISSUE TITLE
Allow enabling IPv6

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/ofono#36]
It appears that UT will only configure the IPv4 address via mobile data, even if the provider supports IPv6. The APN configuration menu lacks an option to set the protocol to IPv6 or IPv4/IPv6. Actually, ofono seems to have the option (see https://github.com/DynamicDevices/ofono/blob/master/doc/connman-api.txt, line 199):
```
string Protocol [readwrite]

			Holds the protocol for this context.  Valid values
			are: "ip", "ipv6" and "dual".
```
Can the UT user interface be changed to allow enabling this option?

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/lomiri-system-settings-cellular/-/issues/2

Sorry for your inconvenience.
